<?php

/**
 * Implements hook_menu().
 */
function smwyg_menu() {
  $items = [];

  //@todo: have a better name than page
  $items['admin/content/smwyg/add'] = [
    'title' => "Create a new {page}",
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['smwyg_create_new_form'],
    'access callback' => TRUE,
  ];

  return $items;
}


function smwyg_create_new_form($form, $form_state) {

  $form['item_path'] = [
    '#type' => 'textfield',
    '#title' => t('Path'),
    '#required' => TRUE,
  ];

  // get node type list
  $node_types = node_type_get_types();

  $form['node_type'] = [
    '#type' => 'select',
    '#title' => t('Node type'),
    '#options' => array_keys($node_types),
    '#required' => TRUE,
  ];

  // Build the sortable table header.
  $header = [
    'title'   => ['data' => t('Title'), 'field' => 'n.title',],
    'type'  => ['data' => t('Type'), 'field' => 'n.type',],
    'author'  => t('Author'),
    'status'  => ['data' => t('Status'), 'field' => 'n.status',],
    'changed' => [
      'data' => t('updated'),
      'field' => 'n.changed',
      'sort' => 'desc',
    ],

  ];

  //Get the node data.
  $q = db_select('node', 'n')
//    ->range(0,10)
    ->fields('n', ['nid'])
//    ->condition('type', 'article')
  ;

  $nids = $q->execute()->fetchCol();
  $nodes = node_load_multiple($nids);
  $options = [];
  foreach ($nodes as $node) {
    $options[$node->nid] = [
      'title' => $node->title,
      'type' => $node->type,
      'author' => theme('username', ['account' => $node]),
      'status' => $node->status ? t('published') : t('not published'),
      'changed' => format_date($node->changed, 'short'),
    ];
    $titles[$node->nid] = $node->title;
  }


  //@todo: select what to use to display the 'pick a node' part to the user.
  $form['node_select'] = array(
    '#type' => 'select',
    '#title' => 'test',
    '#options' => $titles,
    '#multiple' => TRUE,
    '#size' => 50,
  );

  $form['node_table'] = [
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $options,
    '#empty' => t('No content'),
  ];



  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit!'),
  );

  return $form;
}

function smwyg_create_new_form_validate($form, $form_state) {

}
function smwyg_create_new_form_submit($form, $form_state) {

}
